[platformio]
# Cache build supaya kompilasi berikutnya lebih cepat.
build_cache_dir = .pio/build_cache
; packages_dir = .pio/packages

[env]
# Platform ESP32 versi fixed supaya build lebih stabil.
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
platform_packages =
    ; Pakai Arduino core terbaru dari repo Espressif.
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.3.7
extra_scripts =
    ; Script ini menyiapkan toolchain dan esptool saat build.
    pre:tools/setup_toolchain.py
    pre:tools/setup_esptool.py
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize
lib_deps =
    ; Library untuk parsing JSON konfigurasi dan respons web.
    bblanchon/ArduinoJson@^7.4.2
    ; Driver LCD I2C.
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    ; Web server asinkron agar UI responsif.
    esp32async/ESPAsyncWebServer@^3.9.4
    ; Library sensor suhu/kelembapan.
    https://github.com/Sensirion/arduino-sht.git#v1.2.6
    ; Library keypad 4x4.
    chris--a/Keypad@^3.1.1
# File system internal untuk simpan config dan file kecil lain.
board_build.filesystem = littlefs
# Skema partisi kecil untuk proyek ini.
board_build.partitions = min_spiffs.csv
build_unflags =
    -std=gnu++11
    -std=gnu++17
    -std=gnu++20
build_flags =
    ; Pakai standar C++ yang lebih baru.
    -std=gnu++23
    -mlongcalls
    -O3
    -Wall
    -Wextra
    -Wdouble-promotion
    -Wformat=2
    -Wformat-truncation
    -fno-common
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections

[env:esp32dev]

[env:esp32dev_ota]
upload_protocol = espota
upload_port = monitor-server.local
upload_flags = 
    --port=3232
    --host_port=3233
